### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by luli1341f** [Leepee/CSGO4broadcast_Gamestate_to_CSV#1]
hii, how is that supposed to work?
Aston Broadcast CG software is that free? when I search for the software it is not free unfortunately

**Comment by Leepee** [comment]
Hi! 
Unfortunately, the software isn't free. It's a broadcast character generation software that's used for overlays and graphics in sports etc. 

This project is actually very specific to an Aston project that we're using to run up an Esports event, so it's not particularly useful to most people!
